export const PASSENGER_INFORMATION_SESSION_KEY: string =
  "passenger_information";
export const RECENT_AIRPORT_SEARCH_KEY: string = "RECENT_AIRPORT_SEARCH";
export const SELECTED_FLIGHT_SESSION_KEY: string = "selected_flight";

export const PHONE_CODES: {
  name: string;
  emoji: string;
  timezone: string;
  dial_code: string;
}[] = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    emoji: "🇦🇫",
    timezone: "Asia/Kabul",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    emoji: "🇦🇽",
    timezone: "Europe/Mariehamn",
  },
  {
    name: "Albania",
    dial_code: "+355",
    emoji: "🇦🇱",
    timezone: "Europe/Tirane",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    emoji: "🇩🇿",
    timezone: "Africa/Algiers",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    emoji: "🇦🇸",
    timezone: "Pacific/Pago_Pago",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    emoji: "🇦🇩",
    timezone: "Europe/Andorra",
  },
  {
    name: "Angola",
    dial_code: "+244",
    emoji: "🇦🇴",
    timezone: "Africa/Luanda",
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    emoji: "🇦🇮",
    timezone: "America/Anguilla",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    emoji: "🇦🇶",
    timezone: "Antarctica/McMurdo",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    emoji: "🇦🇬",
    timezone: "America/Antigua",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    emoji: "🇦🇷",
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    emoji: "🇦🇲",
    timezone: "Asia/Yerevan",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    emoji: "🇦🇼",
    timezone: "America/Aruba",
  },
  {
    name: "Australia",
    dial_code: "+61",
    emoji: "🇦🇺",
    timezone: "Australia/Sydney",
  },
  {
    name: "Austria",
    dial_code: "+43",
    emoji: "🇦🇹",
    timezone: "Europe/Vienna",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    emoji: "🇦🇿",
    timezone: "Asia/Baku",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    emoji: "🇧🇸",
    timezone: "America/Nassau",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    emoji: "🇧🇭",
    timezone: "Asia/Bahrain",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    emoji: "🇧🇩",
    timezone: "Asia/Dhaka",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    emoji: "🇧🇧",
    timezone: "America/Barbados",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    emoji: "🇧🇾",
    timezone: "Europe/Minsk",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    emoji: "🇧🇪",
    timezone: "Europe/Brussels",
  },
  {
    name: "Belize",
    dial_code: "+501",
    emoji: "🇧🇿",
    timezone: "America/Belize",
  },
  {
    name: "Benin",
    dial_code: "+229",
    emoji: "🇧🇯",
    timezone: "Africa/Porto-Novo",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    emoji: "🇧🇲",
    timezone: "Atlantic/Bermuda",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    emoji: "🇧🇹",
    timezone: "Asia/Thimphu",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    emoji: "🇧🇴",
    timezone: "America/La_Paz",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    emoji: "🇧🇦",
    timezone: "Europe/Sarajevo",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    emoji: "🇧🇼",
    timezone: "Africa/Gaborone",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    emoji: "🇧🇷",
    timezone: "America/Sao_Paulo",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    emoji: "🇮🇴",
    timezone: "Indian/Chagos",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    emoji: "🇧🇳",
    timezone: "Asia/Brunei",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    emoji: "🇧🇬",
    timezone: "Europe/Sofia",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    emoji: "🇧🇫",
    timezone: "Africa/Ouagadougou",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    emoji: "🇧🇮",
    timezone: "Africa/Bujumbura",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    emoji: "🇰🇭",
    timezone: "Asia/Phnom_Penh",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    emoji: "🇨🇲",
    timezone: "Africa/Douala",
  },
  {
    name: "Canada",
    dial_code: "+1",
    emoji: "🇨🇦",
    timezone: "America/Toronto",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    emoji: "🇨🇻",
    timezone: "Atlantic/Cape_Verde",
  },
  {
    name: "Cayman Islands",
    dial_code: "+345",
    emoji: "🇰🇾",
    timezone: "America/Cayman",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    emoji: "🇨🇫",
    timezone: "Africa/Bangui",
  },
  {
    name: "Chad",
    dial_code: "+235",
    emoji: "🇹🇩",
    timezone: "Africa/Ndjamena",
  },
  {
    name: "Chile",
    dial_code: "+56",
    emoji: "🇨🇱",
    timezone: "America/Santiago",
  },
  {
    name: "China",
    dial_code: "+86",
    emoji: "🇨🇳",
    timezone: "Asia/Shanghai",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    emoji: "🇨🇽",
    timezone: "Indian/Christmas",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    emoji: "🇨🇨",
    timezone: "Indian/Cocos",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    emoji: "🇨🇴",
    timezone: "America/Bogota",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    emoji: "🇰🇲",
    timezone: "Indian/Comoro",
  },
  {
    name: "Congo",
    dial_code: "+242",
    emoji: "🇨🇬",
    timezone: "Africa/Brazzaville",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    emoji: "🇨🇩",
    timezone: "Africa/Kinshasa",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    emoji: "🇨🇰",
    timezone: "Pacific/Rarotonga",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    emoji: "🇨🇷",
    timezone: "America/Costa_Rica",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    emoji: "🇨🇮",
    timezone: "Africa/Abidjan",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    emoji: "🇭🇷",
    timezone: "Europe/Zagreb",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    emoji: "🇨🇺",
    timezone: "America/Havana",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    emoji: "🇨🇾",
    timezone: "Asia/Nicosia",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    emoji: "🇨🇿",
    timezone: "Europe/Prague",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    emoji: "🇩🇰",
    timezone: "Europe/Copenhagen",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    emoji: "🇩🇯",
    timezone: "Africa/Djibouti",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    emoji: "🇩🇲",
    timezone: "America/Dominica",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    emoji: "🇩🇴",
    timezone: "America/Santo_Domingo",
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    emoji: "🇪🇨",
    timezone: "America/Guayaquil",
  },
  {
    name: "Egypt",
    dial_code: "+20",
    emoji: "🇪🇬",
    timezone: "Africa/Cairo",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    emoji: "🇸🇻",
    timezone: "America/El_Salvador",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    emoji: "🇬🇶",
    timezone: "Africa/Malabo",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    emoji: "🇪🇷",
    timezone: "Africa/Asmara",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    emoji: "🇪🇪",
    timezone: "Europe/Tallinn",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    emoji: "🇪🇹",
    timezone: "Africa/Addis_Ababa",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    emoji: "🇫🇰",
    timezone: "Atlantic/Stanley",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    emoji: "🇫🇴",
    timezone: "Atlantic/Faroe",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    emoji: "🇫🇯",
    timezone: "Pacific/Fiji",
  },
  {
    name: "Finland",
    dial_code: "+358",
    emoji: "🇫🇮",
    timezone: "Europe/Helsinki",
  },
  {
    name: "France",
    dial_code: "+33",
    emoji: "🇫🇷",
    timezone: "Europe/Paris",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    emoji: "🇬🇫",
    timezone: "America/Cayenne",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    emoji: "🇵🇫",
    timezone: "Pacific/Tahiti",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    emoji: "🇬🇦",
    timezone: "Africa/Libreville",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    emoji: "🇬🇲",
    timezone: "Africa/Banjul",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    emoji: "🇬🇪",
    timezone: "Asia/Tbilisi",
  },
  {
    name: "Germany",
    dial_code: "+49",
    emoji: "🇩🇪",
    timezone: "Europe/Berlin",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    emoji: "🇬🇭",
    timezone: "Africa/Accra",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    emoji: "🇬🇮",
    timezone: "Europe/Gibraltar",
  },
  {
    name: "Greece",
    dial_code: "+30",
    emoji: "🇬🇷",
    timezone: "Europe/Athens",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    emoji: "🇬🇱",
    timezone: "America/Godthab",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    emoji: "🇬🇩",
    timezone: "America/Grenada",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    emoji: "🇬🇵",
    timezone: "America/Guadeloupe",
  },
  {
    name: "Guam",
    dial_code: "+1671",
    emoji: "🇬🇺",
    timezone: "Pacific/Guam",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    emoji: "🇬🇹",
    timezone: "America/Guatemala",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    emoji: "🇬🇬",
    timezone: "Europe/Guernsey",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    emoji: "🇬🇳",
    timezone: "Africa/Conakry",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    emoji: "🇬🇼",
    timezone: "Africa/Bissau",
  },
  {
    name: "Guyana",
    dial_code: "+592",
    emoji: "🇬🇾",
    timezone: "America/Guyana",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    emoji: "🇭🇹",
    timezone: "America/Port-au-Prince",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    emoji: "🇻🇦",
    timezone: "Europe/Vatican",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    emoji: "🇭🇳",
    timezone: "America/Tegucigalpa",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    emoji: "🇭🇰",
    timezone: "Asia/Hong_Kong",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    emoji: "🇭🇺",
    timezone: "Europe/Budapest",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    emoji: "🇮🇸",
    timezone: "Atlantic/Reykjavik",
  },
  {
    name: "India",
    dial_code: "+91",
    emoji: "🇮🇳",
    timezone: "Asia/Kolkata",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    emoji: "🇮🇩",
    timezone: "Asia/Jakarta",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    emoji: "🇮🇷",
    timezone: "Asia/Tehran",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    emoji: "🇮🇷",
    timezone: "Asia/Baghdad",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    emoji: "🇮🇪",
    timezone: "Europe/Dublin",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    emoji: "🇮🇲",
    timezone: "Europe/Isle_of_Man",
  },
  {
    name: "Israel",
    dial_code: "+972",
    emoji: "🇮🇱",
    timezone: "Asia/Jerusalem",
  },
  {
    name: "Italy",
    dial_code: "+39",
    emoji: "🇮🇹",
    timezone: "Europe/Rome",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    emoji: "🇯🇲",
    timezone: "America/Jamaica",
  },
  {
    name: "Japan",
    dial_code: "+81",
    emoji: "🇯🇵",
    timezone: "Asia/Tokyo",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    emoji: "🇯🇪",
    timezone: "Europe/Jersey",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    emoji: "🇯🇴",
    timezone: "Asia/Amman",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    emoji: "🇰🇿",
    timezone: "Asia/Almaty",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    emoji: "🇰🇪",
    timezone: "Africa/Nairobi",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    emoji: "🇰🇮",
    timezone: "Pacific/Tarawa",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    emoji: "🇰🇵",
    timezone: "Asia/Pyongyang",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    emoji: "🇰🇷",
    timezone: "Asia/Seoul",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    emoji: "🇰🇼",
    timezone: "Asia/Kuwait",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    emoji: "🇰🇬",
    timezone: "Asia/Bishkek",
  },
  {
    name: "Laos",
    dial_code: "+856",
    emoji: "🇱🇦",
    timezone: "Asia/Vientiane",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    emoji: "🇱🇻",
    timezone: "Europe/Riga",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    emoji: "🇱🇧",
    timezone: "Asia/Beirut",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    emoji: "🇱🇸",
    timezone: "Africa/Maseru",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    emoji: "🇱🇷",
    timezone: "Africa/Monrovia",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    emoji: "🇱🇾",
    timezone: "Africa/Tripoli",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    emoji: "🇱🇮",
    timezone: "Europe/Vaduz",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    emoji: "🇱🇹",
    timezone: "Europe/Vilnius",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    emoji: "🇱🇺",
    timezone: "Europe/Luxembourg",
  },
  {
    name: "Macao",
    dial_code: "+853",
    emoji: "🇲🇴",
    timezone: "Asia/Macau",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    emoji: "🇲🇰",
    timezone: "Europe/Skopje",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    emoji: "🇲🇬",
    timezone: "Indian/Antananarivo",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    emoji: "🇲🇼",
    timezone: "Africa/Blantyre",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    emoji: "🇲🇾",
    timezone: "Asia/Kuala_Lumpur",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    emoji: "🇲🇻",
    timezone: "Indian/Maldives",
  },
  {
    name: "Mali",
    dial_code: "+223",
    emoji: "🇲🇱",
    timezone: "Africa/Bamako",
  },
  {
    name: "Malta",
    dial_code: "+356",
    emoji: "🇲🇹",
    timezone: "Europe/Malta",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    emoji: "🇲🇭",
    timezone: "Pacific/Majuro",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    emoji: "🇲🇶",
    timezone: "America/Martinique",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    emoji: "🇲🇷",
    timezone: "Africa/Nouakchott",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    emoji: "🇲🇺",
    timezone: "Indian/Mauritius",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    emoji: "🇾🇹",
    timezone: "Indian/Mayotte",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    emoji: "🇲🇽",
    timezone: "America/Mexico_City",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    emoji: "🇫🇲",
    timezone: "Pacific/Chuuk",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    emoji: "🇲🇩",
    timezone: "Europe/Chisinau",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    emoji: "🇲🇨",
    timezone: "Europe/Monaco",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    emoji: "🇲🇳",
    timezone: "Asia/Ulaanbaatar",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    emoji: "🇲🇪",
    timezone: "Europe/Podgorica",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    emoji: "🇲🇸",
    timezone: "America/Montserrat",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    emoji: "🇲🇦",
    timezone: "Africa/Casablanca",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    emoji: "🇲🇿",
    timezone: "Africa/Maputo",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    emoji: "🇲🇲",
    timezone: "Asia/Yangon",
  },
  {
    name: "Namibia",
    emoji: "🇳🇦",
    dial_code: "+264",
    timezone: "Africa/Windhoek",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    emoji: "🇳🇷",
    timezone: "Pacific/Nauru",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    emoji: "🇳🇵",
    timezone: "Asia/Kathmandu",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    emoji: "🇳🇱",
    timezone: "Europe/Amsterdam",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    emoji: "🇧🇶",
    timezone: "America/Curacao",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    emoji: "🇳🇨",
    timezone: "Pacific/Noumea",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    emoji: "🇳🇿",
    timezone: "Pacific/Auckland",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    emoji: "🇳🇮",
    timezone: "America/Managua",
  },
  {
    name: "Niger",
    dial_code: "+227",
    emoji: "🇳🇪",
    timezone: "Africa/Niamey",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    emoji: "🇳🇬",
    timezone: "Africa/Lagos",
  },
  {
    name: "Niue",
    dial_code: "+683",
    emoji: "🇳🇺",
    timezone: "Pacific/Niue",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    emoji: "🇳🇫",
    timezone: "Pacific/Norfolk",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    emoji: "🇲🇵",
    timezone: "Pacific/Saipan",
  },
  {
    name: "Norway",
    dial_code: "+47",
    emoji: "🇳🇴",
    timezone: "Europe/Oslo",
  },
  {
    name: "Oman",
    dial_code: "+968",
    emoji: "🇴🇲",
    timezone: "Asia/Muscat",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    emoji: "🇵🇰",
    timezone: "Asia/Karachi",
  },
  {
    name: "Palau",
    dial_code: "+680",
    emoji: "🇵🇼",
    timezone: "Pacific/Palau",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    emoji: "🇵🇸",
    timezone: "Asia/Hebron",
  },
  {
    name: "Panama",
    dial_code: "+507",
    emoji: "🇵🇦",
    timezone: "America/Panama",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    emoji: "🇵🇬",
    timezone: "Pacific/Port_Moresby",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    emoji: "🇵🇾",
    timezone: "America/Asuncion",
  },
  {
    name: "Peru",
    dial_code: "+51",
    emoji: "🇵🇪",
    timezone: "America/Lima",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    emoji: "🇵🇭",
    timezone: "Asia/Manila",
  },
  {
    name: "Pitcairn",
    dial_code: "+872",
    emoji: "🇵🇳",
    timezone: "Pacific/Pitcairn",
  },
  {
    name: "Poland",
    dial_code: "+48",
    emoji: "🇵🇱",
    timezone: "Europe/Warsaw",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    emoji: "🇵🇹",
    timezone: "Europe/Lisbon",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    emoji: "🇵🇷",
    timezone: "America/Puerto_Rico",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    emoji: "🇶🇦",
    timezone: "Asia/Qatar",
  },
  {
    name: "Romania",
    dial_code: "+40",
    emoji: "🇷🇴",
    timezone: "Europe/Bucharest",
  },
  {
    name: "Russia",
    dial_code: "+7",
    emoji: "🇷🇺",
    timezone: "Europe/Kaliningrad",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    emoji: "🇷🇼",
    timezone: "Africa/Kigali",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    emoji: "🇷🇪",
    timezone: "Indian/Reunion",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    emoji: "🇧🇱",
    timezone: "America/St_Barthelemy",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    emoji: "🇸🇭",
    timezone: "Atlantic/St_Helena",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    emoji: "🇰🇳",
    timezone: "America/St_Kitts",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    emoji: "🇱🇨",
    timezone: "America/St_Lucia",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    emoji: "🇲🇫",
    timezone: "America/Marigot",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    emoji: "🇵🇲",
    timezone: "America/Miquelon",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    emoji: "🇻🇨",
    timezone: "America/St_Vincent",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    emoji: "🇼🇸",
    timezone: "Pacific/Apia",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    emoji: "🇸🇲",
    timezone: "Europe/San_Marino",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    emoji: "🇸🇹",
    timezone: "Africa/Sao_Tome",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    emoji: "🇸🇦",
    timezone: "Asia/Riyadh",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    emoji: "🇸🇳",
    timezone: "Africa/Dakar",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    emoji: "🇷🇸",
    timezone: "Europe/Belgrade",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    emoji: "🇸🇨",
    timezone: "Indian/Mahe",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    emoji: "🇸🇱",
    timezone: "Africa/Freetown",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    emoji: "🇸🇬",
    timezone: "Asia/Singapore",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    emoji: "🇸🇰",
    timezone: "Europe/Bratislava",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    emoji: "🇸🇮",
    timezone: "Europe/Ljubljana",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    emoji: "🇸🇧",
    timezone: "Pacific/Guadalcanal",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    emoji: "🇸🇴",
    timezone: "Africa/Mogadishu",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    emoji: "🇿🇦",
    timezone: "Africa/Johannesburg",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    emoji: "🇸🇸",
    timezone: "Africa/Juba",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    emoji: "🇬🇸",
    timezone: "Atlantic/South_Georgia",
  },
  {
    name: "Spain",
    dial_code: "+34",
    emoji: "🇪🇸",
    timezone: "Europe/Madrid",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    emoji: "🇱🇰",
    timezone: "Asia/Colombo",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    emoji: "🇸🇩",
    timezone: "Africa/Khartoum",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    emoji: "🇸🇷",
    timezone: "America/Paramaribo",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    emoji: "🇸🇯",
    timezone: "Arctic/Longyearbyen",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    emoji: "🇸🇿",
    timezone: "Africa/Mbabane",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    emoji: "🇸🇪",
    timezone: "Europe/Stockholm",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    emoji: "🇨🇭",
    timezone: "Europe/Zurich",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    emoji: "🇸🇾",
    timezone: "Asia/Damascus",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    emoji: "🇹🇼",
    timezone: "Asia/Taipei",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    emoji: "🇹🇯",
    timezone: "Asia/Dushanbe",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    emoji: "🇹🇿",
    timezone: "Africa/Dar_es_Salaam",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    emoji: "🇹🇭",
    timezone: "Asia/Bangkok",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    emoji: "🇹🇱",
    timezone: "Asia/Dili",
  },
  {
    name: "Togo",
    dial_code: "+228",
    emoji: "🇹🇬",
    timezone: "Africa/Lome",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    emoji: "🇹🇰",
    timezone: "Pacific/Fakaofo",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    emoji: "🇹🇴",
    timezone: "Pacific/Tongatapu",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    emoji: "🇹🇹",
    timezone: "America/Port_of_Spain",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    emoji: "🇹🇳",
    timezone: "Africa/Tunis",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    emoji: "🇹🇷",
    timezone: "Europe/Istanbul",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    emoji: "🇹🇲",
    timezone: "Asia/Ashgabat",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    emoji: "🇹🇨",
    timezone: "America/Grand_Turk",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    emoji: "🇹🇻",
    timezone: "Pacific/Funafuti",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    emoji: "🇺🇬",
    timezone: "Africa/Kampala",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    emoji: "🇺🇦",
    timezone: "Europe/Kiev",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    emoji: "🇦🇪",
    timezone: "Asia/Dubai",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    emoji: "🇬🇧",
    timezone: "Europe/London",
  },
  {
    name: "United States",
    dial_code: "+1",
    emoji: "🇺🇸",
    timezone: "America/New_York",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    emoji: "🇺🇾",
    timezone: "America/Montevideo",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    emoji: "🇺🇿",
    timezone: "Asia/Samarkand",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    emoji: "🇻🇺",
    timezone: "Pacific/Efate",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    emoji: "🇻🇪",
    timezone: "America/Caracas",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    emoji: "🇻🇳",
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    emoji: "🇻🇬",
    timezone: "America/Tortola",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    emoji: "🇻🇮",
    timezone: "America/St_Thomas",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    emoji: "🇼🇫",
    timezone: "Pacific/Wallis",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    emoji: "🇾🇪",
    timezone: "Asia/Aden",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    emoji: "🇿🇲",
    timezone: "Africa/Lusaka",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    emoji: "🇿🇼",
    timezone: "Africa/Harare",
  },
];
